# permissions for end users to view hotels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hotel-viewer-role
rules:
- apiGroups:
  - webapp.tsutsumi.io
  resources:
  - hotels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.tsutsumi.io
  resources:
  - hotels/status
  verbs:
  - get
