# permissions for end users to edit hotels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hotel-editor-role
rules:
- apiGroups:
  - webapp.tsutsumi.io
  resources:
  - hotels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.tsutsumi.io
  resources:
  - hotels/status
  verbs:
  - get
