# example manifest for the Guestbook kind
apiVersion: v1
kind: Namespace
metadata:
  name: guestbook-test
---
apiVersion: webapp.tsutsumi.io/v1
kind: Guestbook
metadata:
  namespace: guestbook-test
  name: guestbook-example
spec:
  foo: example2
  # implicitly references Hotel objects
  fooRef:
    name: hotel-example
    namespace: guestbook-test
---
apiVersion: webapp.tsutsumi.io/v1
kind: Hotel
metadata:
  namespace: guestbook-test
  name: hotel-example
spec:
  ok: true
---